# Generated by Django 5.2.7 on 2025-10-15 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'departments'},
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('department_subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.departments')),
            ],
            options={
                'verbose_name_plural': 'subjects.html',
            },
        ),
    ]
