# Generated by Django 5.2.7 on 2025-10-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_subjects_options_subjects_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours_per_Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('hours_subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subjects')),
            ],
        ),
    ]
