# Generated by Django 5.2.7 on 2025-10-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_hours_per_week'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hours_per_Week',
            new_name='HoursperWeek',
        ),
    ]
