# Generated by Django 5.2.7 on 2025-11-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_subjecttopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttopics',
            name='topics_subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_subjects', to='school_app.subjects'),
        ),
    ]
