# Generated by Django 5.2.7 on 2025-11-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_subjecttopics_topics_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject', to='school_app.subjects')),
            ],
        ),
    ]
